repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-toml
    - id: check-yaml
    - id: debug-statements
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-byte-order-marker
    - id: mixed-line-ending
    - id: name-tests-test
    - id: no-commit-to-branch
    - id: trailing-whitespace
- repo: local
  hooks:
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [python]
    - id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types: [python]
    - id: interrogate
      name: interrogate
      entry: poetry run interrogate
      language: system
      types_or: [python, toml]
      pass_filenames: false # KLUDGE: https://github.com/econchick/interrogate/issues/60#issuecomment-735436566
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [python]
    - id: mypy
      name: mypy
      entry: poetry run mypy ./src ./tests
      language: system
      types: [python]
      pass_filenames: false
    - id: pydocstyle
      name: pydocstyle
      entry: poetry run pydocstyle
      language: system
      types: [python]
    - id: pytest
      name: pytest
      entry: poetry run pytest
      language: system
      types: [python]
- repo: https://github.com/zricethezav/gitleaks
  rev: v7.6.1
  hooks:
    - id: gitleaks
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.20.0
  hooks:
    - id: commitizen
      stages:
        - commit-msg
